In [9]:
import torch
print(torch.__version__) 

1.3.1+cpu


In [10]:
text = "ଶେଷରେ ବିଜୟ ହେଲା ସତ୍ୟର। ଦୀର୍ଘ ୭ ବର୍ଷ ପରେ ସ୍ୱାମୀ ତାଙ୍କ ହଜିଲା ସ୍ତ୍ରୀର ଠିକଣା ପାଇଲେ। ନିଜକୁ ନିର୍ଦ୍ଦେଷ ବୋଲି ସାବ୍ୟସ୍ତ କଲେ ସ୍ୱାମୀ।  ହେଲେ ଯେତେବେଳେ ସ୍ତ୍ରୀର ସନ୍ଧାନ ପାଇଲେ ସେତେବେଳେ ସେ ଆଉ କାହାର ହୋଇ ଯାଇଥିଲେ। ତଥାପି ଦୋଷ ନକରି ବି ତାଙ୍କୁ ୭ ବର୍ଷ କାଳ ଦୋଷୀର ବଦନାମ ମୁଣ୍ଡାଇ ବଞ୍ଚିବାକୁ ପଡିଲା।"

In [11]:
from inltk.inltk import tokenize
from inltk.inltk import get_embedding_vectors

In [ ]:
tokenize(text , 'or')

In [40]:
vectors = get_embedding_vectors(text, 'or')

/home/deepak/Documents/answer_evaluator/venv/lib/python3.6/site-packages/torch/serialization.py:493: SourceChangeWarning: source code of class 'torch.nn.modules.loss.CrossEntropyLoss' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/home/deepak/Documents/answer_evaluator/venv/lib/python3.6/site-packages/torch/serialization.py:493: SourceChangeWarning: source code of class 'fastai.text.models.awd_lstm.AWD_LSTM' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/home/deepak/Documents/answer_evaluator/venv/lib/python3.6/site-packages/torch/serialization.py:493: SourceChangeWarning: source code of class 'torch.nn.modules.sparse.Embe

In [43]:
l = len(vectors)
l

63

In [ ]:
get_embedding_vectors(text, 'or')

In [44]:
len(vectors)

63

In [ ]:
len(tokenize(text, 'or'))

In [5]:
import numpy as np

In [45]:
vectors

[array([-0.592143,  0.036464,  1.064776, -0.029495, ..., -0.760284, -0.099626,  0.371477,  0.43619 ], dtype=float32),
 array([ 0.071335,  0.478509,  0.514669,  0.431564, ...,  0.595439, -0.056706,  0.206724,  0.048993], dtype=float32),
 array([ 0.288555,  0.512494,  0.99378 , -0.405916, ...,  0.455619,  0.404982, -0.844652, -0.014613], dtype=float32),
 array([-0.33625 , -0.340926, -0.008408,  0.250804, ...,  0.560029,  0.750533,  0.596823,  0.711635], dtype=float32),
 array([ 2.485659e-01, -1.070712e+00,  2.831249e-01,  2.747490e-02, ...,  7.670560e-01,  6.109239e-01, -7.677363e-02,
        -8.528004e-04], dtype=float32),
 array([ 0.890594,  0.80546 ,  0.060229,  0.146133, ...,  0.135298, -0.083667, -0.511793,  0.464783], dtype=float32),
 array([ 0.097847, -0.029737, -0.114579,  0.366081, ..., -0.103041,  0.500068,  0.623969, -0.439608], dtype=float32),
 array([-0.256353,  0.111601,  0.419539,  0.263737, ...,  0.855219, -0.19227 ,  0.437447,  0.35305 ], dtype=float32),
 array([ 0.18353

In [46]:
vectors = np.asarray(vectors, np.float32)

In [47]:
vectors = vectors.flatten()

In [48]:
len(vectors)

25200

In [49]:
vectors

array([-0.592143,  0.036464,  1.064776, -0.029495, ...,  0.135298, -0.083667, -0.511793,  0.464783], dtype=float32)

In [53]:
vectors = vectors.tolist()

In [54]:
len(vectors)

25200

In [55]:
vectors.extend([0] * ((211-l)*400))

In [56]:
len(vectors)

84400

In [ ]:
vector = []
for _ in vectors:
    vector.append(list(_))
vector

In [24]:
len(vector)

63

In [26]:
len(vector[0])

400

In [ ]:
data1 = [[1,2,3],[4,5,6]]
# data_np = np.asarray(data, np.float32)

In [ ]:
data1

In [ ]:
data_np = np.asarray(data1, np.float32)

In [ ]:
data_np

In [ ]:
import tensorflow as tf

In [ ]:
data_tf = tf.convert_to_tensor(data_np, np.float32)

In [ ]:
tf.print(data_tf)

In [8]:
vectors =  np.asarray(vectors, np.float32)
vectors

array([[-0.592143,  0.036464,  1.064776, -0.029495, ..., -0.760284, -0.099626,  0.371477,  0.43619 ],
       [ 0.071335,  0.478509,  0.514669,  0.431564, ...,  0.595439, -0.056706,  0.206724,  0.048993],
       [ 0.288555,  0.512494,  0.99378 , -0.405916, ...,  0.455619,  0.404982, -0.844652, -0.014613],
       [-0.33625 , -0.340926, -0.008408,  0.250804, ...,  0.560029,  0.750533,  0.596823,  0.711635],
       ...,
       [ 0.551423, -0.806831,  0.336608,  0.054315, ...,  0.590744, -0.592565,  0.135596,  0.672341],
       [-0.210347,  0.313058,  0.462045,  0.66087 , ..., -0.590786,  0.579258, -0.536817, -0.012552],
       [ 0.230717,  0.197861, -0.260078, -0.265133, ..., -0.622642,  0.098941, -0.346819, -0.342401],
       [ 0.890594,  0.80546 ,  0.060229,  0.146133, ...,  0.135298, -0.083667, -0.511793,  0.464783]], dtype=float32)